export const VERB_RADAR_DATE_PICKER_ID = 'VERB_RADAR_DATE_PICKER_ID';
export const VERB_BAR_DATE_PICKER_ID = 'VERB_BAR_DATE_PICKER_ID';
export const VERB_LINE_DATE_PICKER_ID = 'VERB_LINE_DATE_PICKER_ID';
export const VERB_LINE_AVG_LEGEND_ID = 'VERB_LINE_AVG_LEGEND_ID';
export const VERB_BAR_AVG_LEGEND_ID = 'VERB_BAR_AVG_LEGEND_ID';
